import type { Spell } from "../core/types"

// Field geometry reminder: lanes are ½ apart (y ∈ {−1, −½, 0, ½, 1}) and a wizard's
// hitbox is ±0.18, so a shot's spread (σ at the target) of ~0.1 is "reliable" and ~0.3 is a gamble.

export const Spells: Record<string, Spell> = {
    // ---- Attacks ----
    firebolt: {
        id: "firebolt",
        name: "Firebolt",
        kind: "attack",
        element: "fire",
        cost: 1,
        damage: 1,
        beta0: { mean: 0, sd: 0.05 },
        beta1: { mean: 0, sd: 0.08 },
        visual: "projectile",
        description: "A dependable bolt of flame.",
    },
    frost_ray: {
        id: "frost_ray",
        name: "Frost Ray",
        kind: "attack",
        element: "frost",
        cost: 2,
        damage: 1,
        beta0: { mean: 0, sd: 0.02 },
        beta1: { mean: 0, sd: 0.03 },
        visual: "ray",
        description: "Slow to channel, but almost never strays.",
    },
    chain_lightning: {
        id: "chain_lightning",
        name: "Chain Lightning",
        kind: "attack",
        element: "storm",
        cost: 1,
        damage: 2,
        beta0: { mean: 0, sd: 0.14 },
        beta1: { mean: 0, sd: 0.2 },
        visual: "bolt",
        description: "Devastating — if it lands.",
    },
    meteor: {
        id: "meteor",
        name: "Meteor",
        kind: "attack",
        element: "fire",
        cost: 2,
        damage: 3,
        beta0: { mean: 0, sd: 0.1 },
        beta1: { mean: 0, sd: 0.28 },
        visual: "projectile",
        description: "Huge, and hugely unpredictable.",
    },
    ember: {
        id: "ember",
        name: "Ember",
        kind: "attack",
        element: "fire",
        cost: 0,
        damage: 1,
        beta0: { mean: 0, sd: 0.12 },
        beta1: { mean: 0, sd: 0.22 },
        visual: "projectile",
        description: "Free to fling. Wobbly as anything.",
    },

    // ---- Modifiers ----
    shift: {
        id: "shift",
        name: "Shift",
        symbol: "β₀",
        kind: "modifier",
        element: "arcane",
        cost: 1,
        dBeta0: 0.5,
        description: "Raise or lower where your next spell starts.",
    },
    tilt: {
        id: "tilt",
        name: "Tilt",
        symbol: "β₁",
        kind: "modifier",
        element: "arcane",
        cost: 1,
        dBeta1: 0.5,
        description: "Angle your next spell up or down.",
    },
    focus: {
        id: "focus",
        name: "Focus",
        symbol: "σ ÷ 2",
        kind: "modifier",
        element: "arcane",
        cost: 1,
        sdScale: 0.5,
        description: "Halve the spread of your next spell.",
    },
    arc: {
        id: "arc",
        name: "Arc",
        symbol: "β₀+½, β₁−½",
        kind: "modifier",
        element: "arcane",
        cost: 1,
        dBeta0: 0.5,
        dBeta1: -0.5,
        description: "Start higher, aim down: lob it over a wall.",
    },
    nudge: {
        id: "nudge",
        name: "Nudge",
        symbol: "β₀ ¼",
        kind: "modifier",
        element: "arcane",
        cost: 0,
        dBeta0: 0.25,
        description: "A free quarter-lane shift. Small, but free.",
    },

    // ---- Movement ----
    blink: {
        id: "blink",
        name: "Blink",
        kind: "move",
        element: "nature",
        cost: 1,
        step: 0.5,
        description: "Step one lane up or down.",
    },
    leap: {
        id: "leap",
        name: "Leap",
        kind: "move",
        element: "nature",
        cost: 1,
        step: 1,
        description: "Bound two lanes at once.",
    },

    // ---- Wards & hexes ----
    ward: {
        id: "ward",
        name: "Ward",
        kind: "ward",
        element: "shadow",
        cost: 1,
        distance: 0.5,
        halfHeight: 0.15,
        enemyOnly: true,
        description: "A wall at mid-field that absorbs one shot.",
    },
    doodle_wall: {
        id: "doodle_wall",
        name: "Doodle Wall",
        kind: "ward",
        element: "shadow",
        cost: 1,
        distance: 0.5,
        halfHeight: 0.15,
        description: "Scribble a wall at mid-field. Blocks one shot.",
    },
    jinx: {
        id: "jinx",
        name: "Jinx",
        symbol: "σ × 2",
        kind: "hex",
        element: "shadow",
        cost: 1,
        sdScale: 2,
        enemyOnly: true,
        description: "Doubles the opponent's spread next turn.",
    },
    smudge: {
        id: "smudge",
        name: "Smudge",
        symbol: "σ × 2",
        kind: "hex",
        element: "shadow",
        cost: 1,
        sdScale: 2,
        description: "Smear their lines: their spread doubles next turn.",
    },
}

export function getSpell(id: string): Spell {
    const spell = Spells[id]
    if (!spell) throw new Error(`Unknown spell: ${id}`)
    return spell
}
